spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/fitness-bro
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug

jwt:
  token:
    secret: "1234123412341234123412341234123412341234123412341234123412341234"